import animacaoScroll from "./animacaoscroll.js";
import ativarFaq from "./ativarfaq.js";
import mostrarModal from "./modal.js";
import initScrollSuave from "./scrollsuave.js";
import trocarDescricao from "./trocardescricao.js";
import initToolTip from "./tooltip.js";
import initDropDown from "./dropdown.js";
import activeBurgButton from "./menubutton.js";
import initAnimaNumeros from "./anima-numeros.js";
import initFuncionamento from "./funcionamento.js";

animacaoScroll();
ativarFaq();
initScrollSuave();
trocarDescricao();
mostrarModal();
initToolTip();
initDropDown();
activeBurgButton();
initAnimaNumeros();
initFuncionamento();
